spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jrtt?serverTimezone=GMT
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  velocity:
    suffix: .html
    expose-session-attributes: true

mybatis:
  config-location: classpath:mybatis.xml

server:
  port: 80

web:
  upload-path: D:/upload
